### ISSUE TITLE
Update ubooquity to v 1.7

### ISSUE THREAD

**Issue by CaptInsano** [HurricaneHernandez/ubooquity#1]
Hi Hurricane,

Would you mind updating your Dockerfile to the newest ubooquity version?

http://vaemendis.net/ubooquity/downloads/Ubooquity-1.7.0.zip

Version 1.7 enables OPDS feeds!
Thanks a million.

**Comment by HurricaneHernandez** [comment]
You can update it yourself, just replace the jar file in the config folder
with the new version.

**Comment by HurricaneHernandez** [comment]
Obviously stop the container before doing so.

**Comment by CaptInsano** [comment]
Done

Thank you!!
